Initial Qutemonkey Flatpak
AudMonkey/AudMonkey pull request #80
Opened 2021-09-10 15:29 UTC by TheEvilSkeleton

Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

- [ ] I made sure the code compiles on my machine
- [ ] I made sure there are no unnecessary changes in the code
- [ ] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

2021-09-10 16:40 UTC, IshoAntar requested changes

2021-09-10 16:40 UTC, IshoAntar commented on linux/packages/flatpak/com.github.AudMonkey.AudMonkey.yaml
> +      - -Daudmonkey_has_networking=no
This is redundant as networking features (and options) were removed a while ago and will be ignored by CMake.

2021-09-10 16:40 UTC, IshoAntar commented on linux/packages/flatpak/com.github.AudMonkey.AudMonkey.yaml
> +      - -Daudacity_conan_enabled=Off
This should be `-Daudmonkey_conan_enabled=Off`. That was an oversight on my part when renaming stuff.

2021-09-10 16:40 UTC, IshoAntar commented on linux/packages/flatpak/com.github.AudMonkey.AudMonkey.yaml
> +      - /share/audacity/include
Is the `audacity` path necessary?

2021-09-10 16:53 UTC, IshoAntar commented
Regarding my earlier comment about making this work for any branch, looking at the workflow file, this should be a fairly straight-forward thing to do.

This is after you get it working as it is now, of course.

The `flatpak` job can be copy-pasted as it is into the `build-and-deploy` workflow (and renamed to `build-flatpak` for consistency), and the artifact (the Flatpak package) uploaded to the workflow artifacts. After that publishing the release asset will be automatically handled by the release jobs.

2021-09-10 19:03 UTC, TheEvilSkeleton commented on linux/packages/flatpak/com.github.AudMonkey.AudMonkey.yaml
> +      - /share/audacity/include
Not really, but since this is a fork of Audacity, some things might've been left out.

2021-09-10 19:38 UTC, TheEvilSkeleton commented
@IshoAntar can you help me for this? https://github.com/TheEvilSkeleton/AudMonkey/runs/3570558009?check_suite_focus=true#step:4:1978

2021-09-10 19:44 UTC, IshoAntar commented
> @IshoAntar can you help me for this? [TheEvilSkeleton/AudMonkey/runs/3570558009?check_suite_focus=true#step:4:1978](https://github.com/TheEvilSkeleton/AudMonkey/runs/3570558009?check_suite_focus=true#step:4:1978)

That is used to set the package name. e.g. `audmonkey-<AUDMONKEY_SYSTEM_NAME>-x86_64-...` (to differentiate Linux distro packages). You can set it using an environment variable with the same name (like `AUDMONKEY_SYSTEM_NAME=flatpak`).

2021-09-10 21:06 UTC, TheEvilSkeleton commented
@IshoAntar like this? https://github.com/AudMonkey/AudMonkey/pull/80/commits/ccc8188115c7ad739b05248ac326f249fcf88ba5

2021-09-10 21:52 UTC, IshoAntar commented
> @IshoAntar like this? ccc8188

That wouldn't have worked because the variable needs to be exported as an environment variable.

I just pushed a commit that enables setting it on the command line, please pull the latest commit from `qutemonkey` and that should work.

2021-09-11 04:27 UTC, TheEvilSkeleton commented
@IshoAntar

First successful build! https://github.com/TheEvilSkeleton/AudMonkey/pull/1/checks?check_run_id=3573194666 (pardon me for the bundle name).

The only problem is that it fails to load:

```
$ flatpak run com.github.AudMonkey.AudMonkey
audmonkey: error while loading shared libraries: lib-string-utils.so: cannot open shared object file: No such file or directory
```

The workaround at the moment is running `flatpak run --env=LD_LIBRARY_PATH=/app/lib/audmonkey com.github.AudMonkey.AudMonkey`, but the app doesn't launch at all, and doesn't output anything.

2021-09-11 15:17 UTC, IshoAntar commented
> First successful build! TheEvilSkeleton/AudMonkey#1 (checks) (pardon me for the bundle name).

Hooray!

> The only problem is that it fails to load:
> 
> ```
> $ flatpak run com.github.AudMonkey.AudMonkey
> audmonkey: error while loading shared libraries: lib-string-utils.so: cannot open shared object file: No such file or directory
> ```

Interesting. At first glance i thought it would be related to #70, but that only happens when RPATH is not set, does flatpak remove that by any chance? Or where does it load shared libraries from by default? The [docs](https://docs.flatpak.org/en/latest/dependencies.html) didn't say anything about how an executable accesses the required libraries.

> The workaround at the moment is running flatpak run --env=LD_LIBRARY_PATH=/app/lib/audmonkey com.github.AudMonkey.AudMonkey, but the app doesn't launch at all, and doesn't output anything. I get exit status 255 but I don't know what that means.

I'm pretty sure that's related to #68, which does the following:

```sh
$ audmonkey
Unhandled unknown exception; terminating the application.
$ echo $?
255
```

reverted the commit on my fork since it caused more bugs than it actually fixed, i'll submit a PR and we'll see what happens.

2021-09-11 15:23 UTC, TheEvilSkeleton commented
> Interesting. At first glance i thought it would be related to #70, but that only happens when RPATH is not set, does flatpak remove that by any chance? Or where does it load shared libraries from by default? The [docs](https://docs.flatpak.org/en/latest/dependencies.html) didn't say anything about how an executable accesses the required libraries.

It should load libraries under `/app/lib`.

2021-09-11 15:28 UTC, IshoAntar commented
> It should load from /app/lib

OK, it is related to the issue i mentioned then, see **Additional context** (in that issue) for why that happens, the workaround for now is setting `LD_LIBRARY_PATH` as you did.

2021-09-11 15:41 UTC, TheEvilSkeleton commented
@IshoAntar it works! Although, it doesn't look like it's using Qt?

2021-09-11 15:46 UTC, IshoAntar commented
> @IshoAntar it works!

Awesome!

> Although, it doesn't look like it's using Qt?

It's not full-Qt yet, no.

Does it open the QtQuick window or only the wxWidgets one? It should have 2, something like this https://github.com/AudMonkey/AudMonkey/pull/27#issuecomment-903820182

Also this this https://github.com/AudMonkey/AudMonkey/discussions/74#discussioncomment-1299636 for the (current) full migration plan.

2021-09-11 15:51 UTC, TheEvilSkeleton commented
> Does it open the QtQuick window or only the wxWidgets one? It should have 2, something like this [#27 (comment)](https://github.com/AudMonkey/AudMonkey/pull/27#issuecomment-903820182)

I believe wxWidgets only. Can you download the artifact at https://github.com/TheEvilSkeleton/AudMonkey/runs/3575530488 and see whether it opens the QtQuick windows? Alternatively, can you tell me how to open the QtQuick window?

2021-09-11 15:57 UTC, IshoAntar commented
> I believe wxWidgets only.

I looked through the CMake configuration used when building, and seems that you didn't pass `-Daudmonkey_use_qt=On` when building. The build documentation for the `qutemonkey` branch needs some serious revising!

2021-09-11 16:06 UTC, TheEvilSkeleton commented
> > I believe wxWidgets only.
> 
> I looked through the CMake configuration used when building, and seems that you didn't pass `-Daudmonkey_use_qt=On` when building. The build documentation for the `qutemonkey` branch needs some serious revising!

Looks like it still opens using wxWidgets?

![image](https://user-images.githubusercontent.com/50847364/132954101-dcb053ad-020d-4571-bf9a-6188ce988c8c.png)

2021-09-11 16:56 UTC, IshoAntar commented
Alright, head-scratching over.

The problem is that the QML files were loaded as modules instead of resources, basically that means they need to be installed with the app in order for the QtQuick window to work.

I'll switch to using the QResource system for now until we have "installable" modules.

2021-09-11 21:08 UTC, TheEvilSkeleton commented
@IshoAntar I just pulled the latest patches, is it supposed to be using Qt?

2021-09-11 22:34 UTC, IshoAntar commented
> @IshoAntar I just pulled the latest patches, is it supposed to be using Qt?

Yes it is using it!

![2021-09-12_01-31](https://user-images.githubusercontent.com/32076082/132963157-3d96d13e-cc07-4de8-8474-7663f530abf1.png)

That's all the Qt that we have yet. More stuff are coming shortly!

2021-09-12 00:10 UTC, TheEvilSkeleton commented
How did you get that window to show up?

2021-09-12 00:14 UTC, IshoAntar commented
It just does?

I downloaded the artifact from https://github.com/TheEvilSkeleton/AudMonkey/actions/runs/1224949113
`flatpak install audmonkey.flatpak` then run it `flatpak run com.github.AudMonkey.AudMonkey`.

That's the expected behavior. Are you not seeing this for some reason?

2021-09-12 00:18 UTC, TheEvilSkeleton commented
Oh wow! That window was just hiding behind AudMonkey! I was playing around with the main AudMonkey window thinking that it should've been in Qt.

2021-09-12 00:21 UTC, IshoAntar commented
Yeah, my plan is to keep the wxWidgets window functional and remove stuff from it
as they're added to the Qt side.
So the application stays fully-functional (even though not as stable as it should be) during the whole process.

2021-12-30 04:02 UTC, TheEvilSkeleton commented
Closing because of https://github.com/AudMonkey/AudMonkey/commit/e92b0b85986d51e40fcccb41fec61bd261fc52e6.

2021-12-30 04:02 UTC, closed without merging